version: 2

models:
  - name: dim_apps_scd
    description: "SCD Type 2 apps dimension built from snapshot"
    columns:
      - name: app_sk
        tests:
          - not_null
          - unique
      - name: app_id
        tests:
          - not_null

  - name: dim_developers
    columns:
      - name: developer_key
        tests:
          - not_null
          - unique

  - name: dim_categories
    columns:
      - name: category_key
        tests:
          - not_null
          - unique

  - name: dim_date
    columns:
      - name: date_key
        tests:
          - not_null
          - unique

  - name: fact_reviews
    columns:
      - name: review_id
        tests:
          - not_null
          - unique
      - name: app_key
        tests:
          - relationships:
              to: ref('dim_apps_scd')
              field: app_sk
      - name: developer_key
        tests:
          - relationships:
              to: ref('dim_developers')
              field: developer_key
      - name: date_key
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
